# Generated by Django 5.1.3 on 2024-12-05 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CurrentWeather',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=100)),
                ('temperature', models.FloatField()),
                ('precip', models.FloatField()),
                ('humidity', models.FloatField()),
                ('wind_kph', models.FloatField()),
            ],
        ),
    ]
